#Autoconfirms the duel when the players are (see autoconfirm_distance) blocks apart
use_distance_to_autoconfirm: false
#set number of blocks the autoconfirming should use
autoconfirm_distance: 10
#Customize the distance message
custom_distance_message: "2Move {distance} more blocks backwards"
#######################################
#The distance the player has to be to another player to send a duel to them
dual_distance: 20
#Time to count down at the start of a duel
count_down: 5
#Customize the countdown message
count_down_message: "4Get Ready! Time until duel: {time}"
#Amount of time a Duel should last in seconds
Duel_time: 15
#Message to show when a player wins
kill_message: "2{victor} has killed {loser} in a duel!"

